[env:teensy41]
platform = https://github.com/platformio/platform-teensy.git
board = teensy41
framework = arduino

monitor_speed = 115200

build_flags =
    -D CORE_DEBUG_LEVEL=5
    -D USB_MTPDISK_SERIAL
    -include Arduino.h

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.2